"use client";

import { useState } from "react";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { useRouter } from "next/navigation";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [menuOpen, setMenuOpen] = useState(false);
  // const router = useRouter();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-800`}
      >
        <header className="bg-white shadow-md py-10 md:py-4 fixed top-0 left-0 w-full z-50">
          <div className="max-w-6xl mx-auto px-4 flex items-center justify-between relative">
            {/* ロゴ：常に中央配置 */}
            <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 md:static md:translate-x-0 md:translate-y-0 flex-1 flex justify-center md:justify-start">
              <Link href="/">
                <Image
                  src="images/Ubatan-logo.png"
                  alt="Ubatan ロゴ"
                  width={120} // ← 必須: 適切な幅を指定
                  height={40} // ← 必須: 適切な高さを指定
                  className="h-10 w-auto cursor-pointer"
                  priority
                />
              </Link>
            </div>
            {/* PCナビ */}
            <nav className="hidden md:flex items-center space-x-6 ml-auto">
              <a
                href="#products"
                className="text-gray-700 hover:text-blue-500 font-medium"
              >
                パン一覧
              </a>
              <a
                href="#mypage"
                className="text-gray-700 hover:text-blue-500 font-medium"
              >
                マイページ
              </a>
              <a
                href="#cart"
                className="text-gray-700 hover:text-blue-500 font-medium flex items-center"
              >
                カート <span className="ml-1">🛒</span>
              </a>
            </nav>
            {/* ハンバーガーアイコン（モバイル右） */}
            <button
              className="md:hidden flex items-center p-2 rounded hover:bg-gray-100 transition absolute right-0 top-1/2 -translate-y-1/2"
              aria-label="メニューを開く"
              onClick={() => setMenuOpen(!menuOpen)}
            >
              <svg
                width="28"
                height="28"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M4 6h16M4 12h16M4 18h16"
                />
              </svg>
            </button>
          </div>
          {/* モバイルメニュー */}
          {menuOpen && (
            <div className="md:hidden bg-white shadow-lg absolute top-full left-0 w-full z-50 animate-fade-in">
              <nav className="flex flex-col items-center py-4 space-y-2">
                <a
                  href="#products"
                  className="text-gray-700 hover:text-blue-500 font-medium w-full text-center py-2"
                  onClick={() => setMenuOpen(false)}
                >
                  パン一覧
                </a>
                <a
                  href="#mypage"
                  className="text-gray-700 hover:text-blue-500 font-medium w-full text-center py-2"
                  onClick={() => setMenuOpen(false)}
                >
                  マイページ
                </a>
                <a
                  href="#cart"
                  className="text-gray-700 hover:text-blue-500 font-medium w-full text-center py-2 flex justify-center items-center"
                  onClick={() => setMenuOpen(false)}
                >
                  カート <span className="ml-1">🛒</span>
                </a>
              </nav>
            </div>
          )}
        </header>
        <div className="h-[72px] md:h-[64px]" />
        <main className="mx-auto ">{children}</main>
        <footer className="bg-gray-100 py-8 mt-12">
          <div className="max-w-6xl mx-auto text-center text-sm text-gray-500 space-y-2">
            <div className="flex flex-wrap justify-center gap-4 mb-2">
              <a href="#shop" className="hover:underline">
                店舗情報
              </a>
              <a href="#faq" className="hover:underline">
                よくある質問
              </a>
              <a href="#contact" className="hover:underline">
                お問い合わせ
              </a>
              <a href="#law" className="hover:underline">
                特商法表記
              </a>
              <a href="#privacy" className="hover:underline">
                プライバシーポリシー
              </a>
            </div>
            <div className="flex justify-center space-x-4">
              <a
                href="https://instagram.com"
                target="_blank"
                rel="noopener noreferrer"
              >
                Instagram
              </a>
              <a href="https://x.com" target="_blank" rel="noopener noreferrer">
                X
              </a>
            </div>
            <div>© 2025 Ubatan. All rights reserved.</div>
          </div>
        </footer>
      </body>
    </html>
  );
}
