import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 text-gray-800`}
      >
        <header className="bg-white shadow-md py-4">
          <div className="max-w-6xl mx-auto px-4">
            <h1 className="text-2xl font-bold">Panaderia Ubatan</h1>
          </div>
        </header>
        <main className="max-w-6xl mx-auto px-4 py-8">{children}</main>
        <footer className="bg-gray-100 py-4 mt-8">
          <div className="max-w-6xl mx-auto text-center text-sm text-gray-500">
            © 2025 Breadstore. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
